name: Checks

on: [push, pull_request, workflow_dispatch, workflow_call]

jobs:
  check:
    strategy:
      matrix:
        command:
          - nix flake check --accept-flake-config
          - nix run nixpkgs#alejandra -- -c .

    uses: ./.github/workflows/prelude.yml
    secrets: inherit
    with:
      command: ${{ matrix.command }}
