name: Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    strategy:
      matrix:
        command:
          - nix flake check --accept-flake-config
          - nix run nixpkgs#alejandra -- -c .

    uses: ./.github/workflows/nix.yml
    with:
      command: ${{ matrix.command }}
