name: Setup (Go 1.21)

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      platform:
        required: true
        type: string
jobs:
  go-setup:
    runs-on: "${{ inputs.platform }}-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: cd ${{ inputs.path }} && go build -v
